import os

DEPL_BASE_URL = "https://api-free.deepl.com/v2/translate"
DEEPL_API_KEY = os.environ.get("DEEPL_API_KEY")
IGNORE_WORDS = [
    "None",
    "True",
    "False",
    "Id",
    "UnitId",
    "ELVIS",
    "EVR",
    "ID",
    "FSC_COC",
    "FSC_COC/FM",
    "PEFC_COC",
    "FSC_FM",
    "FSC_CW/FM",
    "PEFC_FC",
    "PEFC_GFC",
    "FM/COC",
    "FSC 100%",
    "FSC Mix 10%",
    "FSC Mix 20%",
    "FSC Mix 30%",
    "FSC Mix 40%",
    "FSC Mix 50%",
    "FSC Mix 60%",
    "FSC Mix 70%",
    "FSC Mix 80%",
    "FSC Mix 90%",
    "FSC Mix Credit",
    "FSC Controlled Wood",
    "FSC Mix xx,x%",
    "PEFC Controlled Sources",
    "CompanyCertificate",
    "CompanyAssortment",
    "AssortmentMapping",
    "EE",
    "Thorgate",
    "Tallinn",
    "Harjumaa",
]
PATTERN = r"""(?<![_\.])["']([A-Z][^"']*(?:(?!(?<!\\)["']).)*)["'](?![_\w])"""
